FROM golang:1.26.4 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /out/wallet ./cmd/walletsvc

FROM alpine:latest

WORKDIR /app

COPY --from=builder /out/wallet /app/server

COPY /config/ /app/config/
EXPOSE 8090

ENTRYPOINT [ "/app/server" ]