FROM golang:1.26.4 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /out/server ./cmd/server

# ---- STAGE 2: runtime ----
FROM alpine:latest

WORKDIR /app

COPY --from=builder /out/server /app/server

COPY /config/ /app/config
EXPOSE 8080

ENTRYPOINT [ "/app/server" ]