// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/wallet/wallet.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ConstraintId  string                 `protobuf:"bytes,3,opt,name=constraint_id,json=constraintId,proto3" json:"constraint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetConstraintId() string {
	if x != nil {
		return x.ConstraintId
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_wallet_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"\x19proto/wallet/wallet.proto\x12\x06wallet\"c\n" +
	"\x12TransactionRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12#\n" +
	"\rconstraint_id\x18\x03 \x01(\tR\fconstraintId\"-\n" +
	"\x13TransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x94\x01\n" +
	"\rWalletService\x12@\n" +
	"\x05Debit\x12\x1a.wallet.TransactionRequest\x1a\x1b.wallet.TransactionResponse\x12A\n" +
	"\x06Credit\x12\x1a.wallet.TransactionRequest\x1a\x1b.wallet.TransactionResponseB.Z,Go-project/internal/wallet/walletpb;walletpbb\x06proto3"

var (
	file_proto_wallet_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_wallet_proto_rawDescData []byte
)

func file_proto_wallet_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_wallet_proto_rawDesc), len(file_proto_wallet_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_wallet_proto_rawDescData
}

var file_proto_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_wallet_wallet_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: wallet.TransactionRequest
	(*TransactionResponse)(nil), // 1: wallet.TransactionResponse
}
var file_proto_wallet_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.Debit:input_type -> wallet.TransactionRequest
	0, // 1: wallet.WalletService.Credit:input_type -> wallet.TransactionRequest
	1, // 2: wallet.WalletService.Debit:output_type -> wallet.TransactionResponse
	1, // 3: wallet.WalletService.Credit:output_type -> wallet.TransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wallet_wallet_proto_init() }
func file_proto_wallet_wallet_proto_init() {
	if File_proto_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_wallet_proto_rawDesc), len(file_proto_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_wallet_proto = out.File
	file_proto_wallet_wallet_proto_goTypes = nil
	file_proto_wallet_wallet_proto_depIdxs = nil
}
